baseurl = "https://rmrz.ph"
languageCode = "en"
title = "rmrz"
theme = "kiss"
copyright = "This site does not run any external JavaScript, no tracking, no niffnaffs."
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "rmrz" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
description = "this was supposed to be a family's web portal of sorts"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "dcefram"
github = "dcefram"
email = "dcefram@outlook.com"
linkedin = "daniel-cefram-ramirez"
facebook = ""
instagram = ""
codepen = ""
keybase = "dcefram"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[permalinks]
  blog = "/:title/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "toys"
    name = "Toys"
    url = "/toys/"
    weight = 10
