baseurl = "http://danielcefram.com"
languageCode = "en"
title = "Daniel Cefram's"
theme = "kiss"
copyright = "&copy; <a href=\"http://danielcefram.com\">Daniel Cefram</a> 2017"
disqusShortname = "dcefram"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "Daniel Cefram's journey of stupendous imagination" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
description = "Journey of Stupendous Imagination"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "dcefram"
github = "dcefram"
email = "me@danielcefram.com"
linkedin = "daniel-cefram-ramirez"
facebook = ""
instagram = ""
codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true