baseurl = "https://rmrz.ph"
languageCode = "en"
title = "rmrz"
theme = "akin"
copyright = "No fancy copyright. Just <a href='https://creativecommons.org/licenses/by-nc-sa/2.0/uk/'>creative commons</a> | <a href='https://www.goatcounter.com/'>There's some vanity tracking going on, sorry</a> | <a href='https://rmrz.ph/index.xml'>RSS</a>."
# Number of posts per page
Paginate = 10
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
goatcounter = "rmrz" # Goatcounter code, it's the subdomain part (https://{code}.goatcounter.com/count)
enableSocial = true # Adds OpenGraph and Twitter cards
enableUtterances = true # Adds utterances comments to posts
homeTitle = "rmrz" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
description = "This was supposed to be a family portal."
shareBaseUrl = "https://storage.googleapis.com/rmrz-blog.appspot.com/"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "dcefram"
github = "dcefram"
email = ""
linkedin = "daniel-cefram-ramirez"
facebook = ""
instagram = ""
codepen = ""
keybase = "dcefram"

[params.utterances]

repo = "dcefram/blog"   # github repo path
issueTerm = "pathname"  # valid values: pathname, url, title, og:title, <issue-term>,
label = "blog comment"
theme = "boxy-light"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[permalinks]
  blog = "/:title/"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "toys"
    name = "Toys"
    url = "/toys/"
    weight = 10

[deployment]

  [[deployment.targets]]
  name = "rmrz.ph"
  URL = "gs://www.rmrz.ph"

  [[deployment.matchers]]
  # Cache static assets for 1 year.
  pattern = "^.+\\.(js|css|svg|ttf)$"
  cacheControl = "max-age=31536000, no-transform, public"
  gzip = true

  [[deployment.matchers]]
  pattern = "^.+\\.(png|jpg)$"
  cacheControl = "max-age=31536000, no-transform, public"
  gzip = false

  [[deployment.matchers]]
  # Set custom content type for /sitemap.xml
  pattern = "^sitemap\\.xml$"
  contentType = "application/xml"
  gzip = true

  [[deployment.matchers]]
  pattern = "^.+\\.(html|xml|json)$"
  gzip = true


[markup.goldmark.renderer]
unsafe = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80
